import Head from "next/head";
import Hero from "../Components/Hero";
import Layouts from "../Components/Layouts";
import css from '../styles/Home.module.css'
export default function Home() {
  return (
    <Layouts>
      <div className={css.container}>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          
          <Hero />
        </main>
      </div>
    </Layouts>
  );
}

